baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Yixis Playground'
theme = "phantom"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true